/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-11-09 07:42:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_002dorderStats_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/joeunmall-teamproject/workspace_project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/joeun_mall/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/joeunmall-teamproject/workspace_project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/joeun_mall/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1666662048738L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <!--title 페이지에 맞게 수정-->\r\n");
      out.write("    <title>JoEun-admin 주문통계표</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- javascript -->\r\n");
      out.write("    <script src=\"js/jquery-3.6.1.min.js\"></script>\r\n");
      out.write("    <script src=\"js/admin-orderStats.js\"></script>\r\n");
      out.write("    <script src=\"js/admin-orderTable.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!--css-->\r\n");
      out.write("    <!--admin-nav.css는 고정-->\r\n");
      out.write("    <!--페이지별로 추가해야하는 css 파일은 admin-nav.css 아래에 추가-->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"wrap\">\r\n");
      out.write("        <!--관리자 페이지 header 생략-->\r\n");
      out.write("        <nav>\r\n");
      out.write("            <!--a 태그 href는 추후 페이지 완성 후 수정-->\r\n");
      out.write("        	<a href = \"");
      out.print(request.getContextPath());
      out.write("/orderManage.do?admin=team3\">\r\n");
      out.write("				<img id=\"logo\" src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\" alt=\"JoEunMall\">\r\n");
      out.write("			</a>                    \r\n");
      out.write("			<hr id=\"logohr\" />\r\n");
      out.write("            <ul>\r\n");
      out.write("                <!--html 페이지에 해당하는 li태그에 class=\"thispage\" 지정-->\r\n");
      out.write("                <!--class가 \"li-lower\"에 해당하는 경우, 상위 li에도 class=\"thispage\" 지정-->\r\n");
      out.write("                <!--ex) <li class=\"li-lower thispage\"> -->\r\n");
      out.write("                <li><a href=\"admin-orderManage.html\">주문관리</a></li>\r\n");
      out.write("                <li class=\"thispage\"><a href=\"admin-orderStats.html\">주문통계</a></li>\r\n");
      out.write("                <li><a href=\"admin-productManage.html\">상품관리</a></li>\r\n");
      out.write("                <ul class=\"ul-lower\">\r\n");
      out.write("                    <li class=\"li-lower\"><a href=\"admin-productManage.html\">상품조회</a></li>\r\n");
      out.write("                    <li class=\"li-lower\"><a href=\"admin-productRegistration.html\">상품등록</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <li><a href=\"admin-customerManage.html\">고객관리</a></li>\r\n");
      out.write("                <li><a href=\"admin-inquiryManage.html\">1:1문의</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <input type=\"button\" value=\"로그아웃\" id=\"logout-btn\">\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!--admin-nav.css 끝-->\r\n");
      out.write("\r\n");
      out.write("        <section>\r\n");
      out.write("            <!-- 주문 통계 표 페이지 헤더(?) -->\r\n");
      out.write("            <!-- 기간 선택 드랍박스 -->\r\n");
      out.write("            <div id=\"top-menu-manageStats\">\r\n");
      out.write("	            <div>  <!-- 기간 선택 select -->\r\n");
      out.write("	                <select name=\"selectPeriod\" class=\"select3\">\r\n");
      out.write("	                    <option selected>전체 기간</option>\r\n");
      out.write("	                    <option value=\"2209\">2022년 9월</option>\r\n");
      out.write("	                    <option value=\"2208\">2022년 8월</option>\r\n");
      out.write("	                    <option value=\"2207\">2022년 7월</option>\r\n");
      out.write("	                    <option value=\"2206\">2022년 6월</option>\r\n");
      out.write("	                </select>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div>\r\n");
      out.write("	                <!-- 그래프 보기 버튼 -->\r\n");
      out.write("	                <input type=\"button\" value=\"그래프 보기\" id=\"graph-btn\" style=\"cursor:pointer\" onclick=\"location.href='admin-orderStatsGraph.html'\">\r\n");
      out.write("	            </div>\r\n");
      out.write("        	</div>\r\n");
      out.write("            <section id=\"section\">\r\n");
      out.write("            <!-- 테이블 -->\r\n");
      out.write("            <article>\r\n");
      out.write("                <div id=\"bottom-menu-manage\">\r\n");
      out.write("                    <table>\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>No </th>\r\n");
      out.write("                                <th>날짜</th>\r\n");
      out.write("                                <th class=\"th2-width\">상품명</th> <!-- 너비 조절 -->\r\n");
      out.write("                                <th>\r\n");
      out.write("                                    <select name=\"order-state\" class=\"drop-table\">\r\n");
      out.write("                                        <option value=\"os-1\">전체 의류</option>\r\n");
      out.write("                                        <option value=\"os-2\">티셔츠</option>\r\n");
      out.write("                                        <option value=\"os-3\">팬츠/스커트</option>\r\n");
      out.write("                                        <option value=\"os-4\">원피스</option>\r\n");
      out.write("                                        <option value=\"os-5\">니트/가디건</option>\r\n");
      out.write("                                        <option value=\"os-6\">자켓</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </th>\r\n");
      out.write("                                <th style=\"cursor: pointer;\" onclick=\"sortTable(0)\">판매수량&nbsp<img src=\"images/icon/icon_sort.png\" width=20 height=15></th>\r\n");
      out.write("                                <th style=\"cursor: pointer;\" onclick=\"sortTable(1)\">개별 가격&nbsp<img src=\"images/icon/icon_sort.png\" width=20 height=15></th>\r\n");
      out.write("                                <th style=\"cursor: pointer;\" onclick=\"sortTable(2)\">총 판매 금액<img src=\"images/icon/icon_sort.png\" width=20 height=15></th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <!-- 레이아웃 페이지보다 웹페이지가 커서 행 2개 추가 (7개 > 9개) -->\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                                <td>Cell Data</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </article>\r\n");
      out.write("    \r\n");
      out.write("    <!-- paging -->\r\n");
      out.write("            <article>\r\n");
      out.write("                <div class=\"page-wrap\">\r\n");
      out.write("                    <div class=\"page-nation\">\r\n");
      out.write("                        <a class=\"arrow pprev\" href=\"#\"></a>\r\n");
      out.write("                        <a class=\"arrow prev\" href=\"#\"></a>\r\n");
      out.write("                        <a href=\"#\" class=\"active\">1</a>\r\n");
      out.write("                        <a href=\"#\">2</a>\r\n");
      out.write("                        <a href=\"#\">3</a>\r\n");
      out.write("                        <a href=\"#\">4</a>\r\n");
      out.write("                        <a href=\"#\">5</a>\r\n");
      out.write("                        <a class=\"arrow next\" href=\"#\"></a>\r\n");
      out.write("                        <a class=\"arrow nnext\" href=\"#\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </article>\r\n");
      out.write("            \r\n");
      out.write("        </section>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /jsp/admin/admin-orderStats.jsp(23,49) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/css/admin-nav.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /jsp/admin/admin-orderStats.jsp(24,49) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/css/admin-section-manage.css");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /jsp/admin/admin-orderStats.jsp(34,24) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/images/logo/logo_transparent.png");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }
}
